#!/usr/bin/env python3
"""
Merge a patch JSON into an .xcstrings catalog without touching unrelated
keys, key order, or existing translations.

Usage:
    apply.py <catalog.xcstrings> <patch.json> [--allow-source-language]

Patch format:
    {
        "<key>": {
            "comment": "...",                 // optional
            "isCommentAutoGenerated": true,   // optional, only valid with comment
            "localizations": {
                "<lang>": { "stringUnit": { "state": "translated", "value": "..." } },
                "<lang>": { "variations": { "plural": { "one": {...}, "other": {...} } } }
            }
        }
    }

Rules enforced:
  * Source-language writes are refused unless `--allow-source-language` is
    passed. Even with the flag, the writer never overwrites an existing
    translated source-language value; it only fills empty / non-translated
    source slots. (The hard rule "do not modify a translated en value" still
    holds — there is no way to clobber a translated source via this script.)
  * Will not overwrite an existing translated stringUnit (state=="translated")
    in any language.
  * Will not overwrite an existing comment unless the patch sets one AND the
    existing comment was auto-generated (isCommentAutoGenerated true) or absent.
  * Preserves catalog formatting: 2-space indent, sorted keys = false, trailing
    newline. Xcode's xcstrings encoder writes keys sorted alphabetically; we
    match that by re-sorting to keep diffs minimal.
"""
import json
import sys
from pathlib import Path


def is_translated_unit(unit: dict | None) -> bool:
    return bool(unit and unit.get("state") == "translated" and unit.get("value", "") != "")


def merge_localization(existing: dict | None, incoming: dict) -> dict:
    """Merge a single language's localization. Never clobber a translated unit."""
    if existing is None:
        return incoming

    # Plural variations
    if "variations" in incoming:
        out = dict(existing) if existing else {}
        out_var = dict(out.get("variations", {}))
        in_plural = incoming["variations"].get("plural", {})
        out_plural = dict(out_var.get("plural", {}))
        for form, payload in in_plural.items():
            existing_form = out_plural.get(form)
            if existing_form and is_translated_unit(existing_form.get("stringUnit")):
                continue  # respect existing translation
            out_plural[form] = payload
        out_var["plural"] = out_plural
        out["variations"] = out_var
        return out

    # Simple stringUnit
    if "stringUnit" in incoming:
        existing_unit = existing.get("stringUnit") if existing else None
        if is_translated_unit(existing_unit):
            return existing  # do not clobber
        out = dict(existing) if existing else {}
        out["stringUnit"] = incoming["stringUnit"]
        return out

    return existing or incoming


def apply_patch(catalog: dict, patch: dict, allow_source: bool = False) -> tuple[int, int, int, list[str]]:
    src_lang = catalog.get("sourceLanguage", "en")
    strings = catalog.setdefault("strings", {})
    comments_set = 0
    units_set = 0
    source_set = 0
    skipped: list[str] = []

    for key, payload in patch.items():
        entry = strings.get(key)
        if entry is None:
            skipped.append(f"{key}: not in catalog")
            continue
        if entry.get("shouldTranslate") is False:
            skipped.append(f"{key}: shouldTranslate=false")
            continue

        # Comment handling
        if "comment" in payload:
            existing_comment = entry.get("comment")
            existing_auto = entry.get("isCommentAutoGenerated") is True
            if not existing_comment or existing_auto:
                entry["comment"] = payload["comment"]
                if payload.get("isCommentAutoGenerated", True):
                    entry["isCommentAutoGenerated"] = True
                else:
                    entry.pop("isCommentAutoGenerated", None)
                comments_set += 1
            else:
                skipped.append(f"{key}: comment is human-written, not overwritten")

        # Localizations
        if "localizations" in payload:
            locs = entry.setdefault("localizations", {})
            for lang, incoming_loc in payload["localizations"].items():
                if lang == src_lang and not allow_source:
                    skipped.append(f"{key}: source-language ({src_lang}) write requires --allow-source-language")
                    continue
                existing_loc = locs.get(lang)
                merged = merge_localization(existing_loc, incoming_loc)
                if merged is existing_loc:
                    if lang == src_lang and existing_loc is not None:
                        skipped.append(f"{key}: source-language ({src_lang}) already translated, kept")
                    continue
                locs[lang] = merged
                units_set += 1
                if lang == src_lang:
                    source_set += 1

    return comments_set, units_set, source_set, skipped


def main() -> int:
    args = sys.argv[1:]
    allow_source = False
    if "--allow-source-language" in args:
        allow_source = True
        args = [a for a in args if a != "--allow-source-language"]
    if len(args) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    catalog_path = Path(args[0])
    patch_path = Path(args[1])

    catalog = json.loads(catalog_path.read_text(encoding="utf-8"))
    patch = json.loads(patch_path.read_text(encoding="utf-8"))

    comments_set, units_set, source_set, skipped = apply_patch(catalog, patch, allow_source=allow_source)

    catalog_path.write_text(
        json.dumps(catalog, indent=2, ensure_ascii=False, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    msg = f"{catalog_path.name}: comments={comments_set} translations={units_set}"
    if source_set:
        msg += f" (incl. {source_set} source-language)"
    print(msg)
    for s in skipped:
        print(f"  skipped: {s}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
